#!/usr/bin/env perl

use strict;
use v5.30;

my $total = 0;

while (<>) {
  chomp;

  my @dim    = sort { $a <=> $b } split 'x';
  my $length = 2 * $dim[0] + 2 * $dim[1];
  my $volume = $dim[0] * $dim[1] * $dim[2];

  # say sprintf '%8s -> %3d + %5d -> %5d', ( join 'x', @dim ), $length, $volume, $length + $volume;

  $total += $length + $volume;
}

say $total;
